## common config
server:
  tomcat:
    accesslog:
      enabled: true
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev
  aop:
    auto: true
  devtools:
    livereload:
      enabled: true
    restart:
      exclude: static/**
  http:
    encoding:
      charset: UTF-8
  messages:
    encoding: UTF-8
    basename: classpath:i18n/
  application:
    name: llmall-service

mybatis:
  mapper-locations: classpath:mappers/**/*Mapper.xml
  type-aliases-package: biz.llmall.common.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  path: /var/log/llmall
  config: classpath:logback-spring.xml
  
#swagger config
swagger:
  title: 商城API
  description: 提供商品分类、品牌分类和商品列表
  contact:
    name: 刘军
    email: liu1084@gmail.com
  base-package: biz.llmall.commodity
  base-path: /api/**
  exclude-path: /error, /ops/**
  enabled: true

---
# dev
## port
server:
  port: 8080
## database
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/llmall?serverTimezone=UTC&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: liujun
    password: Vtoxibk9qnpWr+1w
  redis:
    host: 127.0.0.1
    port: 6379
    password: ge*u0Oj9X
---